### PR TITLE
Fix documentation link

### PR DESCRIPTION
**Pull request by MuhtasimTanmoy**
Should close https://github.com/owncast/owncast/issues/3581 and https://github.com/owncast/owncast/issues/3579.

### CODE REVIEW

**Comment by gabek** [comment]
I'll provide some background on how these kinds of static site generators work. What you do to build out the content of the site is write a bunch of Markdown files (.md) and then you run the static site generator where it takes each Markdown file and converts it to an actual HTML web page. This means at the end of it all you don't ship Markdown files. If you'd like to learn more there's a ton of documentation out there: https://www.digitalocean.com/community/conceptual-articles/introduction-to-static-site-generators

So this being said, if you linked to a Markdown file, it wouldn't work, because that file wouldn't actually be there.

It says https://owncast.online/docs/sslproxies/caddy/ and https://owncast.online/images/hacktoberfest.jpg are broken links, I'm not sure that's accurate. They look ok to me. The real "fix" to this problem would be fixing any false negatives after seeing they're not actually broken.

My guess is because `caddy/_index.md` converts to the root of a directory (in this case /caddy) something needs to be changed to reflect that. If you actually linked to `_index.md`, it wouldn't work.

And as for that image, I have no guesses what's going on there. Would need to do some digging.

I'm sorry not all of these broken links are as simple as they look. Many of them are, I'm sure, but you'll have to test first to make sure you know what you're fixing and not just blindly make changes.

**Comment by MuhtasimTanmoy** [comment]
> And as for that image, I have no guesses what's going on there. Would need to do some digging.

When we refer to the resources location in relative to from where it is referred it is wrong.
For example,

```
images: ["../images/hacktoberfest.jpg"]

got changed to

images: ["./images/hacktoberfest.jpg"]
```

After this fix it was visible on documentation. 

As for testing should clicking a link in the doc to actually see the referred page appear is necessary? If there is any convention what that is? Building the static site and test from the HTML should be enough?

**Comment by gabek** [comment]
I guess I'm a little confused. You mention it's wrong, but I'm looking at https://owncast.online/hacktoberfest/ and I see the image. It looks ok to me how it is: https://github.com/owncast/owncast.github.io/blob/master/content/hacktoberfest.md?plain=1#L10. Could you share some detail about what's currently wrong with that page?

**Comment by MuhtasimTanmoy** [comment]
Isn't the `images` folder in the same parent directory as the  `hacktoberfest.md`. Should `../images/` this work for referencing the image? I am little confused about any convention as well. I think should close this.

**Pull request closed without merging**
