### PR TITLE
Update install script.

### PR DESCRIPTION
**Pull request by jmhobbs**
A small refactor and update, including:

- Let spinner use the PID of the background process it is spinning for to wait.
- Use a temp dir for downloads to avoid clutter on failures.
- Dry out dependency tool detection and errors.
- Add an exit handler to request bug reports on failure.
- Clear up shellcheck linter issues.
- Add architecture detection for Linux
- Fix a bug with attempting to unzip the ffmpeg binary on Linux

### CODE REVIEW

**Comment by gabek** [comment]
That's so cool!  You really took my "take this script I threw together and fix it up if you want" to heart!  Much more robust and easier to maintain going forward, too.

**Comment by jmhobbs** [comment]
Once 0.3 is released with the 32 bit build I'll do one last test, but then this should be g2g.

**Comment by gabek** [comment]
I think we should merge this in so we can use it ourselves for 0.0.2 installs, even though it won't be fully functional (for all the architectures) until 0.0.3 with the 32 bit builds.  We'll still have time to test that as the script won't be made public until we test the release and installs anyway.  Up to you, though! :)

**Comment by jmhobbs** [comment]
Sure!  Can you add the new binaries onto the release? https://github.com/owncast/owncast/releases/tag/v0.0.2

**Comment by gabek** [comment]
Absolutely!  I'll re-build from [v0.0.2](https://github.com/owncast/owncast/releases/tag/v0.0.2) and replace all the archives to match your script's expected naming convention for the existing files as well.

**Comment by gabek** [comment]
Done!  https://github.com/owncast/owncast/releases/tag/v0.0.2

**Comment by jmhobbs** [comment]
Thanks!  I just tested this on:

- Ubuntu 16.04 x86 VM
- Ubuntu 20.04 x84_64 VM
- Darwin 18.7.0 x86_64 Laptop

Downloads the right files 👍

**Comment by gabek** [comment]
Woohoo!  Awesome, thanks so much John! 🎉

**Pull request merged**
