### PR TITLE
Add storage provider contabo.com

### PR DESCRIPTION
**Pull request by zerodytrash**
Contabo seems to have a good offer. I tested it and it works perfectly!
This PR contains the instructions.

### CODE REVIEW

**Comment by gabek** [comment]
This is great! I wasn't familiar with them. Thank you for testing it out and going through the effort of documenting it,

**Comment by zerodytrash** [comment]
image
For some reason the markdown parser doesn't like my style. My local build does not have this issue 😥

**Comment by gabek** [comment]
Super weird, it looks fine locally for me too! I guess the production rendering of Markdown uses different rules.  I went ahead and just moved the colons and it seems to be happier with that.

**Comment by zerodytrash** [comment]
fine, thank you!

**Pull request merged**
