### PR TITLE
Add support for arm7 in installer (0.0.4)

### PR DESCRIPTION
**Pull request by gabek**

### CODE REVIEW

**Comment by jeyemwey** [comment]
Would you mind, if I merge this into the 0.0.4 branch? Then, we can merge the collected branch when releasing 0.0.4.

**Comment by gabek** [comment]
Sounds good!

**Comment by jeyemwey** [comment]
Good, I'll close this PR then.

**Comment by jeyemwey** [comment]
Merged `gek/add-arm7-installer` into `0.0.4` with 75647b3.

**Pull request closed without merging**
