### PR TITLE
Add object lifecycle rules to CF docs

### PR DESCRIPTION
**Pull request by rmens**
R2 now supports object lifecycle rules. Made some formatting more consistent too.

### CODE REVIEW

**Comment by rmens** [comment]
This is ready for review @gabek

**Comment by gabek** [comment]
Just curious, but why is the serving endpoint required for R2?

**Comment by rmens** [comment]
@gabek The public serving endpoint if different from the S3 endpoint with Cloudflare R2. I confirmed this in the R2 admin interface.

**Comment by gabek** [comment]
Oh got it, thanks!

**Pull request merged**
